# Generated by Django 6.0 on 2025-12-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.FloatField(blank=True, null=True)),
                ('ffa', models.FloatField(blank=True, null=True)),
                ('color_r', models.FloatField(blank=True, null=True)),
                ('color_y', models.FloatField(blank=True, null=True)),
                ('color_b', models.FloatField(blank=True, null=True)),
                ('sfc', models.FloatField(blank=True, null=True)),
                ('iv', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.project')),
            ],
        ),
    ]
